services:
  postgres_cinema:
    image: postgres:16-alpine
    container_name: postgres_cinema
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - theater_network

  redis:
    image: redis:7-alpine
    container_name: redis_cinema
    ports:
      - "6379:6379"
    networks:
      - theater_network

  app:
    build: .
    container_name: cinema_backend
    entrypoint: ""
    depends_on:
      postgres_cinema:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Явно вызываем скрипт по полному пути
    command: /bin/bash /app/commands/entrypoint.sh uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - theater_network

  celery_worker:
    build: .
    container_name: cinema_worker
    entrypoint: ""
    depends_on:
      - redis
      - postgres_cinema
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    volumes:
      - .:/app
    command: /bin/bash /app/commands/entrypoint.sh celery -A app.worker.celery_app worker --loglevel=info
    networks:
      - theater_network

  celery_beat:
    build: .
    container_name: cinema_beat
    entrypoint: ""
    depends_on:
      - redis
      - postgres_cinema
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    volumes:
      - .:/app
    command: /bin/bash /app/commands/entrypoint.sh celery -A app.worker.celery_app beat --loglevel=info
    networks:
      - theater_network

  mailhog:
    image: mailhog/mailhog
    container_name: cinema_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - theater_network

  minio:
    image: minio/minio:latest
    container_name: minio_cinema
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - theater_network

  minio_mc:
    image: minio/mc
    container_name: minio_mc_cinema
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc mb myminio/$${MINIO_STORAGE} || true;
      mc anonymous set download myminio/$${MINIO_STORAGE};
      exit 0;
      "
    networks:
      - theater_network

networks:
  theater_network:
    driver: bridge

volumes:
  pg_data: