"""add_rating_stats_columns_to_movies

Revision ID: b370013e9037
Revises: 5b1c1b049dc9
Create Date: 2026-04-29 22:27:59.503944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b370013e9037'
down_revision: Union[str, Sequence[str], None] = '5b1c1b049dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
