"""add_index_to_tokens_expiry

Revision ID: c7edaa1c8627
Revises: 9a6374b09ce2
Create Date: 2026-04-23 23:09:22.386376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c7edaa1c8627"
down_revision: Union[str, Sequence[str], None] = "9a6374b09ce2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_activation_tokens_expires_at"),
        "activation_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expires_at"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_expires_at"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_activation_tokens_expires_at"), table_name="activation_tokens"
    )
    # ### end Alembic commands ###
