"""soft_delete_movies

Revision ID: d2ebf332a5ec
Revises: df2eabca878b
Create Date: 2026-05-08 15:47:01.045344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d2ebf332a5ec"
down_revision: Union[str, Sequence[str], None] = "df2eabca878b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column(
        "movies", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "deleted_at")
    op.drop_column("movies", "is_deleted")
    # ### end Alembic commands ###
